version: "3.7"
services:
  registry:
    image: registry:2.8.1
    container_name: registry
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    volumes:
      - ./registry-data:/var/lib/registry
      - ./auth:/auth
    networks:
      - docker-registry
    restart: always
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-ui
    environment:
      ENV_DOCKER_REGISTRY_HOST: 192.168.122.231
      ENV_DOCKER_REGISTRY_PORT: 5000
    ports:
      - 8080:80
    networks:
      - docker-registry
    restart: always
networks:
  docker-registry: